#!/bin/bash
set -e

echo "=== Reverse Proxy Setup (Caddy) ==="
echo ""
echo "This script will set up Caddy as a reverse proxy with automatic TLS"
echo "certificates from Let's Encrypt."
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
   echo "Please run as root (sudo)"
   exit 1
fi

# Check for domain name
if [ -z "$1" ]; then
    echo "Usage: $0 <domain-name>"
    echo "Example: $0 www.remote-login.us"
    exit 1
fi

DOMAIN=$1
APP_PORT=58082

echo "Domain: $DOMAIN"
echo "App Port: $APP_PORT"
echo ""

# Check if Caddy is installed
if ! command -v caddy &> /dev/null; then
    echo "[1/5] Installing Caddy..."
    
    # Add Caddy repository
    sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    
    sudo apt update
    sudo apt install -y caddy
    
    echo "✓ Caddy installed"
else
    echo "[1/5] Caddy already installed"
    caddy version
fi

# Create Caddyfile
echo ""
echo "[2/5] Creating Caddyfile..."

CADDYFILE="/etc/caddy/Caddyfile"
BACKUP_FILE="${CADDYFILE}.backup.$(date +%Y%m%d_%H%M%S)"

# Backup existing Caddyfile if it exists
if [ -f "$CADDYFILE" ]; then
    cp "$CADDYFILE" "$BACKUP_FILE"
    echo "  Backed up existing Caddyfile to $BACKUP_FILE"
fi

# Create Caddyfile
cat > "$CADDYFILE" <<EOF
# BitM-NG Reverse Proxy Configuration
# Auto-generated by setup-reverse-proxy.sh

${DOMAIN} {
    # Enable automatic HTTPS with Let's Encrypt
    tls {
        protocols tls1.2 tls1.3
    }

    # Logging
    log {
        output file /var/log/caddy/bitm-ng.log
        format json
    }

    # Reverse proxy to application
    reverse_proxy localhost:${APP_PORT} {
        # WebSocket support for Socket.IO
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        
        # WebSocket upgrade
        header_up Connection {>Connection}
        header_up Upgrade {>Upgrade}
    }

    # Security headers
    header {
        # Remove server information
        -Server
        -X-Powered-By
        
        # Security headers
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        X-XSS-Protection "1; mode=block"
        Referrer-Policy "strict-origin-when-cross-origin"
    }

    # Compression
    encode gzip zstd
}

# Redirect HTTP to HTTPS
http://${DOMAIN} {
    redir https://${DOMAIN}{uri} permanent
}
EOF

echo "✓ Caddyfile created at $CADDYFILE"

# Create log directory
echo ""
echo "[3/5] Setting up logging..."
mkdir -p /var/log/caddy
chown caddy:caddy /var/log/caddy 2>/dev/null || chown root:root /var/log/caddy
echo "✓ Log directory created"

# Enable and start Caddy
echo ""
echo "[4/5] Starting Caddy service..."
systemctl enable caddy
systemctl restart caddy

# Wait for service to start
sleep 2

# Check status
if systemctl is-active --quiet caddy; then
    echo "✓ Caddy service is running"
else
    echo "✗ Caddy service failed to start"
    systemctl status caddy
    exit 1
fi

# Test configuration
echo ""
echo "[5/5] Testing Caddy configuration..."
caddy validate --config "$CADDYFILE"

if [ $? -eq 0 ]; then
    echo "✓ Caddyfile is valid"
else
    echo "✗ Caddyfile validation failed"
    exit 1
fi

# Check firewall
echo ""
echo "=== Firewall Configuration ==="
echo "Ensure ports 80 and 443 are open:"
echo "  sudo ufw allow 80/tcp"
echo "  sudo ufw allow 443/tcp"
echo ""

# Final instructions
echo "=== Setup Complete ==="
echo ""
echo "Caddy is now configured as a reverse proxy:"
echo "  - Domain: $DOMAIN"
echo "  - HTTPS: https://$DOMAIN (automatic Let's Encrypt)"
echo "  - Backend: http://localhost:$APP_PORT"
echo ""
echo "Caddy will automatically:"
echo "  - Obtain Let's Encrypt certificates"
echo "  - Renew certificates automatically"
echo "  - Handle HTTP to HTTPS redirects"
echo ""
echo "To view logs:"
echo "  sudo tail -f /var/log/caddy/bitm-ng.log"
echo ""
echo "To reload Caddy after config changes:"
echo "  sudo systemctl reload caddy"
echo ""
echo "Caddyfile location: $CADDYFILE"
echo ""

